### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by Thefull10** [veger/foei#36] opened 2021-09-15 14:27 UTC
Didn’t see to work on Mac

**Comment by veger** [comment] 2021-09-15 18:48
(Duplicate of #7)

I need more information to be able to solve it (if even possible as I don't own a Mac)

**Closed by veger** 2021-09-15 18:48 UTC

**Comment by Thefull10** [comment] 2021-09-15 18:51
I’ll send over tonight after work.   Does the extension have a gvg fast fight ability as in select sectors and set time between attacks Sent using the mobile mail appOn 15/09/2021 at 19:49, Maarten Bezemer wrote:
                
            
            
                
                    From: "Maarten Bezemer" ***@***.***>Date: 15 September 2021To: "veger/foei" ***@***.***>Cc: "Thefull10" ***@***.***>,"Author" ***@***.***>Subject: Re: [veger/foei] Mac (#36)
                
                
(Duplicate of #7)
I need more information to be able to solve it (if even possible as I don't own a Mac)

**Comment by veger** [comment] 2021-09-15 18:55
>  Does the extension have a gvg fast fight ability as in select sectors and set time between attacks

No the GvG tab only keeps track of known armies, so you can select the best counter measure (AFAIR)

From the REAMDE (main page of the repo)
> ... because FoEI does not send anything to the game servers, it only listens to the incoming traffic ...

So, the extension will _not_ do automated stuff for you. It 'just' analyses the incoming data to give the player an edge (or at the least lets him relax and do the maths for him)

But, feel free to fork this repo and add automation to the fork. For me it is too risky to get detected and banned... :scream:

**Comment by Thefull10** [comment] 2021-09-15 18:59
Ah cheers.  I’m not technical to add a fork, wouldn’t know where to start.  There is a couple of guys who had a script but one is now off line and I can’t get through to the other guy “th3cod3r” he goes by on GitHub.    I had someone look at the code and he said it looks good but the extension won’t load in chromeSent using the mobile mail appOn 15/09/2021 at 19:56, Maarten Bezemer wrote:
                
            
            
                
                    From: "Maarten Bezemer" ***@***.***>Date: 15 September 2021To: "veger/foei" ***@***.***>Cc: "Author" ***@***.***>,"Thefull10" ***@***.***>Subject: Re: [veger/foei] Mac (#36)
                
                



Does the extension have a gvg fast fight ability as in select sectors and set time between attacks



No the GvG tab only keeps track of known armies, so you can select the best counter measure (AFAIR)

From the REAMDE (main page of the repo)



... because FoEI does not send anything to the game servers, it only listens to the incoming traffic ...



So, the extension will not do automated stuff for you. It 'just' analyses the incoming data to give the player an edge (or at the least lets him relax and do the maths for him)

But, feel free to fork this repo and add automation to the fork. For me it is too risky to get detected and banned... 😱
